### ISSUE TITLE
Problems with graph colors against background-front in dark mode

### ISSUE THREAD

**Issue by ecircenis** [grommet/grommet-theme-hpe#32] opened 2020-04-01 21:33 UTC
The graph-2 color is almost undistinguishable from background-front in dark mode.
The graph-0 and graph-4 colors in dark mode are nearly identical to each other.
The graph-1 color has low contrast against background-front.

![image](https://user-images.githubusercontent.com/17883783/78188657-db4f9e80-742d-11ea-8605-6095111afb90.png)

In general, in dark mode, the graph colors should be lighter because they will typically be shown against a background-front color.

**Comment by ShimiSun** [comment] 2020-04-01 21:39
I think the issue is resulted from not using the 'bang' colors.
So in this case if we'll use
`'graph-0': 'orange!',` instead of `'graph-0': 'orange',` we shouldn't have a problem.

https://github.com/grommet/grommet-theme-hpe/blob/6ff15cc51728419e0f7cce4cf4876f0da797e6c2/src/js/index.js#L113

**Comment by ShimiSun** [comment] 2020-04-01 21:44
I've filed a PR to address this issue.

**Comment by ShimiSun** [comment] 2020-04-06 19:58
This issue should be fixed with my recent PR, hence I'll be closing it. Thanks for reporting.

**Closed by ShimiSun** 2020-04-06 19:58 UTC
